# Data Preprocessing

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import pandas as pd
import os
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!ls /content/drive/MyDrive/knowze

sentiment  web_scraping


In [4]:
import os
os.chdir('/content/drive/MyDrive/knowze/sentiment')

In [57]:
# Initiate Var
vocab_size = 20000
embedding_dim = 50
max_length= 20

In [13]:
# Load csv file

dataset = pd.read_csv('data_sentimenv2.csv')

# Cleaning Data
dataset['text'] = dataset['text'].str.lower()  # Ubah ke lowercase
dataset['text'] = dataset['text'].str.replace('[^\w\s]', '')  # Hapus karakter khusus

# Turn Text into list
sentences = dataset['text'].tolist()
labels = dataset['sentiment'].tolist()

for item in range(0,5):
  label = labels[item]
  print(sentences[item] + ' Labels : ')
  print(label)
# print(len(sentences))
# print(len(labels))
print(tf.shape(sentences))
print(tf.size(labels).numpy())

kursus ini sangat membantu dan informatif materi disajikan dengan baik Labels : 
1
materi kurang jelas dan sulit dipahami saya kecewa dengan kursus ini Labels : 
0
instruktur sangat berpengetahuan dan responsif terhadap pertanyaan peserta Labels : 
1
saya merasa rugi telah mengikuti kursus ini tidak sesuai ekspektasi saya Labels : 
0
kursus ini memberikan wawasan yang mendalam tentang topik yang dibahas Labels : 
1
tf.Tensor([590], shape=(1,), dtype=int32)
590


<ipython-input-13-3f8789c8b8c1>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  dataset['text'] = dataset['text'].str.replace('[^\w\s]', '')  # Hapus karakter khusus


In [28]:
max_data_length = tf.size(labels).numpy()
max_data_length

590

In [48]:
# Turn text into tokenizer words
tokenizer = tf.keras.preprocessing.text.Tokenizer(oov_token='OOV')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
# print(word_index)
# Padding Tokenizer
def seq_padding(sentences):
  sequences = tokenizer.texts_to_sequences(sentences)
  padded_seq = tf.keras.preprocessing.sequence.pad_sequences(sequences,maxlen=max_length,padding='post',truncating='post')
  return padded_seq
train_dataset = seq_padding(sentences)
train_dataset = tf.constant(train_dataset)
train_dataset

<tf.Tensor: shape=(590, 20), dtype=int32, numpy=
array([[  6,   9,   3, ...,   0,   0,   0],
       [ 11,   5,  29, ...,   0,   0,   0],
       [ 22,   3, 258, ...,   0,   0,   0],
       ...,
       [  7,  49, 257, ...,   0,   0,   0],
       [  7,  49, 257, ...,   0,   0,   0],
       [  7,  49, 689, ...,   0,   0,   0]], dtype=int32)>

In [49]:
# Persiapan label agar sesuai dengan panjang teks setelah padding
padded_labels = []
for label in labels:
    # padded_label = label[:max_length]  # Ambil sebagian label sesuai dengan panjang teks yang sudah dipad
    padded_labels.append(label)

padded_labels = tf.constant(padded_labels)

# Tampilkan hasil preprocessing
print(padded_labels)

tf.Tensor(
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 1
 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0
 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0
 0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1
 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1

In [83]:
# Shuffle Data
combined_data = tf.data.Dataset.from_tensor_slices((train_dataset, padded_labels))
# print(list(combined_data.as_numpy_iterator())[0])
shuffled_data = combined_data.shuffle(buffer_size=len(train_dataset))

# Define training and validation sets
training_set = shuffled_data.take(500)
validation_set = shuffled_data.skip(500)

# Configure the batch size and prefetch for better performance
batch_size = 32
training_set = training_set.batch(batch_size).prefetch(buffer_size=tf.data.AUTOTUNE)
validation_set = validation_set.batch(batch_size).prefetch(buffer_size=tf.data.AUTOTUNE)

In [54]:
# Split Dataset [Naif]
# training_set = train_dataset[:500]
# validation_set = train_dataset[500:]

# label_training = padded_labels[:500]
# label_validation = padded_labels[500:]

# print(training_set.shape)
# print(label_training.shape)

# print(validation_set.shape)
# print(label_validation.shape)

(500, 20)
(500,)
(90, 20)
(90,)


# Create Model

In [84]:
model = tf.keras.Sequential([
  tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
  tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(140, return_sequences=True)),
  tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(45, return_sequences=True)),
  tf.keras.layers.GlobalAveragePooling1D(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid'),
])
model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)
model.fit(training_set, epochs=30, validation_data=validation_set)

Epoch 1/30
16/16 [==============================] - 23s 326ms/step - loss: 0.6885 - accuracy: 0.5220 - val_loss: 0.7129 - val_accuracy: 0.4556
Epoch 2/30
16/16 [==============================] - 2s 112ms/step - loss: 0.6063 - accuracy: 0.6320 - val_loss: 0.3135 - val_accuracy: 0.9111
Epoch 3/30
16/16 [==============================] - 2s 113ms/step - loss: 0.1917 - accuracy: 0.9400 - val_loss: 0.0794 - val_accuracy: 0.9778
Epoch 4/30
16/16 [==============================] - 2s 114ms/step - loss: 0.0819 - accuracy: 0.9740 - val_loss: 0.0703 - val_accuracy: 0.9778
Epoch 5/30
16/16 [==============================] - 3s 178ms/step - loss: 0.0403 - accuracy: 0.9900 - val_loss: 0.0038 - val_accuracy: 1.0000
Epoch 6/30
16/16 [==============================] - 2s 140ms/step - loss: 0.0237 - accuracy: 0.9940 - val_loss: 0.0044 - val_accuracy: 1.0000
Epoch 7/30
16/16 [==============================] - 2s 108ms/step - loss: 0.0023 - accuracy: 1.0000 - val_loss: 1.7334e-04 - val_accuracy: 1.0000
E

******

# Testing Models

In [89]:
# Testing for sigmoid
# Sample new words for testing
new_words = ["Cara membunuh orang"]

# Preprocess the new words (assuming 'tokenizer' and 'max_length' are from the training phase)
new_sequences = tokenizer.texts_to_sequences(new_words)
new_padded =  tf.keras.preprocessing.sequence.pad_sequences(new_sequences, maxlen=max_length, padding='post', truncating='post')

# Make predictions
predictions = model.predict(new_padded)

get_predict = predictions[0]
print(get_predict)
if get_predict > 0.5:
  print('positif')
else:
  print('negatif')
# Prediksi

1/1 [==============================] - 0s 33ms/step
[7.9049045e-05]
negatif


In [ ]:
# Sample new words for testing
new_words = ["Cara menjadi orang pintar"]

# Preprocess the new words (assuming 'tokenizer' and 'max_length' are from the training phase)
new_sequences = tokenizer.texts_to_sequences(new_words)
new_padded =  tf.keras.preprocessing.sequence.pad_sequences(new_sequences, maxlen=max_length, padding='post', truncating='post')

# Make predictions
predictions = model.predict(new_padded)

# Get class predictions (assuming your classes are labeled as 0, 1, 2)
class_predictions = [tf.argmax(pred).numpy() for pred in predictions]
print(class_predictions)
# Prediksi
labels_word = ['Positif', 'Negatif', 'Neutral']
for i, word in enumerate(new_words):
    print(f"Word: {word}")
    print(f"Predicted Class: {labels_word[class_predictions[i]]}")
    print()

1/1 [==============================] - 0s 51ms/step
[2]
Word: Cara menjadi orang pintar
Predicted Class: Neutral

